services:
  # Drand service for node 1
  drand-1:
    container_name: drand-1
    hostname: drand-1
    image: drand:${DRAND_TAG:-latest}
    env_file:
      - .env
    volumes:
      - ./drand/start_scripts/:/go/drand/scripts/
    entrypoint: /go/drand/scripts/drand-1.sh
    networks:
      antithesis-net:
        ipv4_address: ${DRAND_1_IP}
    healthcheck:
      test: drand util ping http://10.20.20.21:8080
      interval: 5s
      timeout: 2s
      retries: 10
  
  # Drand service for node 2
  drand-2:
    container_name: drand-2
    hostname: drand-2
    image: drand:${DRAND_TAG:-latest}
    env_file:
      - .env
    volumes:
      - ./drand/start_scripts/:/go/drand/scripts/
    entrypoint: /go/drand/scripts/drand-2.sh
    networks:
      antithesis-net:
        ipv4_address: ${DRAND_2_IP}
    depends_on:
      drand-1: 
        condition: service_started
    healthcheck:
      test: drand util ping http://10.20.20.22:8080
      interval: 5s
      timeout: 2s
      retries: 10

  # Drand service for node 3
  drand-3:
    container_name: drand-3
    hostname: drand-3
    image: drand:${DRAND_TAG:-latest}
    env_file:
      - .env
    volumes:
      - ./drand/start_scripts/:/go/drand/scripts/
    entrypoint: /go/drand/scripts/drand-3.sh
    networks:
      antithesis-net:
        ipv4_address: ${DRAND_3_IP}
    depends_on:
      drand-1: 
        condition: service_started
    healthcheck:
      test: drand util ping http://10.20.20.23:8080
      interval: 5s
      timeout: 2s
      retries: 10

  # Lotus node 1 service
  lotus-1:
    container_name: lotus-1
    hostname: lotus-1
    image: lotus:${LOTUS_TAG:-latest}
    volumes:
      - ./data/lotus-1:${LOTUS_1_DATA_DIR}
      - ./lotus/start_scripts/lotus-1.sh:${LOTUS_1_DATA_DIR}/lotus-1.sh
      - ./lotus/lotus_bench.sh:/opt/antithesis/test/v1/main/serial_driver_lotus_bench.sh
      - ./data/forest:${FOREST_DATA_DIR}
      - ./data/lotus-2:${LOTUS_2_DATA_DIR}
    environment:
      - LOTUS_SHARK_HEIGHT=${SHARK_HEIGHT}
      - LOTUS_HYGGE_HEIGHT=${HYGGE_HEIGHT}
      - LOTUS_LIGHTNING_HEIGHT=${LIGHTNING_HEIGHT}
      - LOTUS_THUNDER_HEIGHT=${THUNDER_HEIGHT}
      - LOTUS_WATERMELON_HEIGHT=${WATERMELON_HEIGHT}
      - LOTUS_DRAGON_HEIGHT=${DRAGON_HEIGHT}
      - LOTUS_GENESIS_NETWORK_VERSION=${GENESIS_NETWORK_VERSION}
      - LOTUS_WAFFLE_HEIGHT=${WAFFLE_HEIGHT}
      - LOTUS_TUKTUK_HEIGHT=${TUKTUK_HEIGHT}
      - LOTUS_TEEP_HEIGHT=${TEEP_HEIGHT} 
      - LOTUS_1_IP=${LOTUS_1_IP}
      - LOTUS_GOLDEN_WEEK_HEIGHT=${GOLDENWEEK_HEIGHT}
    env_file:
      - .env
    entrypoint: ["${LOTUS_1_DATA_DIR}/lotus-1.sh"]
    networks:
      antithesis-net:
        ipv4_address: ${LOTUS_1_IP}
    depends_on:
      drand-1: 
        condition: service_healthy
      drand-2:
        condition: service_healthy
      drand-3:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://10.20.20.24:1234/health/livez
      start_period: 20s
      interval: 5s
      timeout: 2s
      retries: 10

  # Lotus miner 1 service
  lotus-miner-1:
    image: lotus:${LOTUS_TAG:-latest}
    container_name: lotus-miner-1
    volumes:
      - ./data/lotus-1:${LOTUS_1_DATA_DIR}
      - ./lotus/start_scripts/lotus-miner-1.sh:${LOTUS_1_DATA_DIR}/lotus-miner-1.sh
    environment:
      - LOTUS_SHARK_HEIGHT=${SHARK_HEIGHT}
      - LOTUS_HYGGE_HEIGHT=${HYGGE_HEIGHT}
      - LOTUS_LIGHTNING_HEIGHT=${LIGHTNING_HEIGHT}
      - LOTUS_THUNDER_HEIGHT=${THUNDER_HEIGHT}
      - LOTUS_WATERMELON_HEIGHT=${WATERMELON_HEIGHT}
      - LOTUS_DRAGON_HEIGHT=${DRAGON_HEIGHT}
      - LOTUS_GENESIS_NETWORK_VERSION=${GENESIS_NETWORK_VERSION}
      - LOTUS_WAFFLE_HEIGHT=${WAFFLE_HEIGHT}
      - LOTUS_MINER_1_IP=${LOTUS_MINER_1_IP}
      - LOTUS_TUKTUK_HEIGHT=${TUKTUK_HEIGHT}
      - LOTUS_TEEP_HEIGHT=${TEEP_HEIGHT}
      - LOTUS_GOLDEN_WEEK_HEIGHT=${GOLDENWEEK_HEIGHT}
    ports:
      - ${LOTUS_MINER_1_RPC_PORT}:${LOTUS_MINER_1_RPC_PORT}
    env_file:
      - .env
    restart: on-failure
    entrypoint: ["${LOTUS_1_DATA_DIR}/lotus-miner-1.sh"]
    networks:
      antithesis-net:
        ipv4_address: ${LOTUS_MINER_1_IP}
    depends_on:
      lotus-1: 
        condition: service_healthy
   
    # Lotus node 2 service
  lotus-2:
    image: lotus:${LOTUS_TAG:-latest}
    hostname: lotus-2
    container_name: lotus-2
    volumes:
      - ./data/lotus-1:${LOTUS_1_DATA_DIR}
      - ./data/lotus-2:${LOTUS_2_DATA_DIR}
      - ./data/forest:${FOREST_DATA_DIR}
      - ./lotus/start_scripts/lotus-2.sh:${LOTUS_2_DATA_DIR}/lotus-2.sh
    environment:
      - LOTUS_SHARK_HEIGHT=${SHARK_HEIGHT}
      - LOTUS_HYGGE_HEIGHT=${HYGGE_HEIGHT}
      - LOTUS_LIGHTNING_HEIGHT=${LIGHTNING_HEIGHT}
      - LOTUS_THUNDER_HEIGHT=${THUNDER_HEIGHT}
      - LOTUS_WATERMELON_HEIGHT=${WATERMELON_HEIGHT}
      - LOTUS_DRAGON_HEIGHT=${DRAGON_HEIGHT}
      - LOTUS_GENESIS_NETWORK_VERSION=${GENESIS_NETWORK_VERSION}
      - LOTUS_WAFFLE_HEIGHT=${WAFFLE_HEIGHT}
      - LOTUS_2_IP=${LOTUS_2_IP}
      - LOTUS_2_RPC_PORT=${LOTUS_2_RPC_PORT}
      - LOTUS_TUKTUK_HEIGHT=${TUKTUK_HEIGHT}
      - LOTUS_TEEP_HEIGHT=${TEEP_HEIGHT}
      - LOTUS_GOLDEN_WEEK_HEIGHT=${GOLDENWEEK_HEIGHT}
    env_file:
      - .env
    entrypoint: ["${LOTUS_2_DATA_DIR}/lotus-2.sh"]
    networks:
      antithesis-net:
        ipv4_address: ${LOTUS_2_IP}
    depends_on:
      lotus-1: 
        condition: service_healthy
    healthcheck:
      test: curl --fail http://10.20.20.26:1235/health/livez
      start_period: 30s
      interval: 5s
      timeout: 2s
      retries: 10

  # Lotus miner 2 service
  lotus-miner-2:
    image: lotus:${LOTUS_TAG:-latest}
    container_name: lotus-miner-2
    volumes:
      - ./data/lotus-2:${LOTUS_2_DATA_DIR}
      - ./lotus/start_scripts/lotus-miner-2.sh:${LOTUS_2_DATA_DIR}/lotus-miner-2.sh
    environment:
      - LOTUS_SHARK_HEIGHT=${SHARK_HEIGHT}
      - LOTUS_HYGGE_HEIGHT=${HYGGE_HEIGHT}
      - LOTUS_LIGHTNING_HEIGHT=${LIGHTNING_HEIGHT}
      - LOTUS_THUNDER_HEIGHT=${THUNDER_HEIGHT}
      - LOTUS_WATERMELON_HEIGHT=${WATERMELON_HEIGHT}
      - LOTUS_DRAGON_HEIGHT=${DRAGON_HEIGHT}
      - LOTUS_GENESIS_NETWORK_VERSION=${GENESIS_NETWORK_VERSION}
      - LOTUS_WAFFLE_HEIGHT=${WAFFLE_HEIGHT}
      - LOTUS_MINER_2_IP=${LOTUS_MINER_2_IP}
      - LOTUS_TUKTUK_HEIGHT=${TUKTUK_HEIGHT}
      - LOTUS_TEEP_HEIGHT=${TEEP_HEIGHT}
      - LOTUS_GOLDEN_WEEK_HEIGHT=${GOLDENWEEK_HEIGHT}
    ports:
      - ${LOTUS_MINER_2_RPC_PORT}:${LOTUS_MINER_2_RPC_PORT}
    env_file:
      - .env
    restart: on-failure
    entrypoint: ["${LOTUS_2_DATA_DIR}/lotus-miner-2.sh"]
    networks:
      antithesis-net:
        ipv4_address: ${LOTUS_MINER_2_IP}
    depends_on:
      lotus-2: 
        condition: service_healthy

  #Forest service
  forest:
    image: forest:${FOREST_COMMIT:-latest}
    container_name: forest
    volumes:
      - ./data/lotus-1:${LOTUS_1_DATA_DIR}
      - ./data/lotus-2:${LOTUS_2_DATA_DIR}
      - ./data/forest:${FOREST_DATA_DIR}
      - ./forest/forest_config.toml.tpl:/forest/forest_config.toml.tpl
      - ./forest/start_scripts/forest-init.sh:${FOREST_DATA_DIR}/forest-init.sh
      - ./forest/forest_bench.sh:/opt/antithesis/test/v1/main/parallel_driver_forest_snapshot_generate.sh
      - ./forest/forest_validate_snapshots.sh:/opt/antithesis/test/v1/main/eventually_forest_snapshot_validate.sh
    environment:
      - FOREST_F3_PERMANENT_PARTICIPATING_MINER_ADDRESSES=${LOTUS_MINER_1_ACTOR_ADDRESS}
      - FOREST_GENESIS_NETWORK_VERSION=${GENESIS_NETWORK_VERSION}
      - FOREST_SHARK_HEIGHT=${SHARK_HEIGHT}
      - FOREST_HYGGE_HEIGHT=${HYGGE_HEIGHT}
      - FOREST_LIGHTNING_HEIGHT=${LIGHTNING_HEIGHT}
      - FOREST_THUNDER_HEIGHT=${THUNDER_HEIGHT}
      - FOREST_WATERMELON_HEIGHT=${WATERMELON_HEIGHT}
      - FOREST_DRAGON_HEIGHT=${DRAGON_HEIGHT}
      - FOREST_WAFFLE_HEIGHT=${WAFFLE_HEIGHT}
      - FOREST_TUKTUK_HEIGHT=${TUKTUK_HEIGHT}
      - FOREST_IP=${FOREST_IP}
      - FOREST_HEALTHZ_RPC_PORT=${FOREST_HEALTHZ_RPC_PORT}
      - FOREST_TEEP_HEIGHT=${TEEP_HEIGHT}
      - FOREST_GOLDEN_WEEK_HEIGHT=${GOLDENWEEK_HEIGHT}
    ports:
      - ${FOREST_RPC_PORT}:${FOREST_RPC_PORT}
    env_file:
      - .env      
    entrypoint: ["${FOREST_DATA_DIR}/forest-init.sh"]
    networks:
      antithesis-net:
        ipv4_address: ${FOREST_IP}
    depends_on:
      lotus-2: 
        condition: service_healthy
    healthcheck:
      test: curl --fail http://10.20.20.28:2346/livez?verbose
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 30s

  # # Curio service
  # curio:
  #   image: curio:latest
  #   container_name: curio
  #   volumes:
  #     - ./data/curio:/var/lib/curio:rw
  #     - ./data/lotus-1:${LOTUS_1_DATA_DIR}
  #     - ./data/lotus-2:${LOTUS_2_DATA_DIR}
  #     - ./data/forest:${FOREST_DATA_DIR}
  #     - ./curio/start_scripts/curio-init.sh:${CURIO_DATA_DIR}/curio-init.sh
  #   env_file:
  #     - .env
  #   environment:
  #     - CURIO_IP=${CURIO_IP}
  #   ports:
  #     - "443:443"
  #     - "80:80"
  #     - "12300:12300"
  #     - "4701:4701"
  #     - "32100:32100"
  #   entrypoint: ["${CURIO_DATA_DIR}/curio-init.sh"]
  #   networks:
  #     antithesis-net:
  #       ipv4_address: ${CURIO_IP}
  #   depends_on:
  #     lotus-1:
  #       condition: service_healthy
  #     yugabyte:
  #       condition: service_started

  #Workload service
  workload:
    image: workload:latest
    container_name: workload
    volumes:
      - ./data/lotus-1:/root/devgen/lotus-1
      - ./data/lotus-2:/root/devgen/lotus-2
      - ./data/forest:/root/devgen/forest
    env_file:
      - .env
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.30
    depends_on:
      lotus-2:
        condition: service_healthy
  # # Yugabyte Database Service
  # yugabyte:
  #   image: yugabytedb/yugabyte:latest
  #   container_name: yugabyte
  #   init: true
  #   command: [ "bin/yugabyted", "start", "--base_dir=/home/yugabyte/yb_data", "--background=false" ]
  #   ports:
  #     - "5433:5433"
  #     - "9042:9042"
  #     - "15433:15433"
  #   environment:
  #     - TINI_SUBREAPER=true
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./data/yugabyte:/home/yugabyte/yb_data
  #   networks:
  #     antithesis-net:
  #       ipv4_address: ${YUGABYTE_IP}

networks:
  antithesis-net:
    ipam:
      config:
        - subnet: 10.20.20.0/24