version: '3.8'

services:
  drand-1:
    container_name: drand-1
    hostname: drand-1
    image: drand:antithesis
    entrypoint: /go/drand/scripts/./drand-1.sh
    volumes:
      - ./drand/start_scripts/:/go/drand/scripts/
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.21

  drand-2:
    container_name: drand-2
    hostname: drand-2
    image: drand:antithesis
    entrypoint: /go/drand/scripts/./drand-2.sh
    volumes:
      - ./drand/start_scripts/:/go/drand/scripts/
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.22

  drand-3:
    container_name: drand-3
    hostname: drand-3
    image: drand:antithesis
    entrypoint: /go/drand/scripts/./drand-3.sh
    volumes:
      - ./drand/start_scripts/:/go/drand/scripts/
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.23

  lotus-1:
    container_name: lotus-1
    hostname: lotus-1
    image: "lotus:${IMAGE_TAG:-antithesis}"
    depends_on:
      - drand-1
    environment:
      LOTUS: lotus-1
      LOTUS_COUNT: 2
      LOTUS_PATH: /root/.lotus
      LOTUS_MINER_PATH: /root/.lotus-miner
      LOTUS_SKIP_GENESIS_CHECK: _yes_
      CGO_CFLAGS_ALLOW: -D__BLST_PORTABLE__
      CGO_CFLAGS: -D__BLST_PORTABLE__
      LOTUS_FEVM_ENABLEETHRPC: true
    entrypoint: /opt/lotus_transformed/customer/entrypoint.sh
    volumes:
      - ./lotus/start_scripts/lotus-leader.sh:/opt/lotus_transformed/customer/entrypoint.sh
      - ./lotus/devgen/:/opt/lotus_transformed/customer/devgen/
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.24

  lotus-2:
    container_name: lotus-2
    hostname: lotus-2
    image: "lotus:${IMAGE_TAG:-antithesis}"
    depends_on:
      - drand-1
      - lotus-1
    environment:
      LOTUS: lotus-2
      LOTUS_COUNT: 2
      LOTUS_PATH: /root/.lotus
      LOTUS_MINER_PATH: /root/.lotus-miner
      LOTUS_SKIP_GENESIS_CHECK: _yes_
      CGO_CFLAGS_ALLOW: -D__BLST_PORTABLE__
      CGO_CFLAGS: -D__BLST_PORTABLE__
      LOTUS_FEVM_ENABLEETHRPC: true
    entrypoint: /opt/lotus_transformed/customer/entrypoint.sh
    volumes:
      - ./lotus/start_scripts/lotus-follower.sh:/opt/lotus_transformed/customer/entrypoint.sh
      - ./lotus/devgen/:/opt/lotus_transformed/customer/devgen/
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.25

  workload:
    container_name: workload
    hostname: workload
    image: "lotus-workload:latest"
    depends_on:
      - drand-1
      - lotus-1
      - lotus-2
    environment:
      RPC_LOTUS1: http://10.20.20.24:1234/rpc/v0
      RPC_LOTUS2: http://10.20.20.25:1234/rpc/v0
      INIT_BLOCK_HEIGHT: 10
    # entrypoint: ["sleep", "infinity"]
    entrypoint: /entrypoint.sh
    volumes:
      - ./workload/fil_spammer_rpc.py:/root/fil_spammer_rpc.py
      - ./workload/entrypoint.sh:/entrypoint.sh
      - ./lotus/devgen/:/root/devgen
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.26

networks:
  antithesis-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.20.0/24
