
import json
import re

TYPE_MAPPING = {
    "TipSetKey": "types.TipSetKey",
    "TipSet": "*types.TipSet",
    "Tipset": "*types.TipSet",
    "Address": "address.Address",
    "Cid": "cid.Cid",
    "ChainEpoch": "abi.ChainEpoch",
    "Height": "abi.ChainEpoch",
    "Actor": "*types.Actor",
    "BlockHeader": "*types.BlockHeader",
    "Message": "*types.Message",
    "SignedMessage": "*types.SignedMessage",
    "KeyInfo": "types.KeyInfo",
    "ActorState": "*types.Actor",
    "IpldObject": "interface{}", # fallback
    "ObjStat": "interface{}", # fallback
}

EXCLUDED_METHODS = {
    # Networking
    "NetAddrsListen", "NetAgentVersion", "NetConnect", "NetDisconnect",
    "NetPeers", "NetProtectAdd", "NetProtectList", "NetProtectRemove",
    # Wallet
    "WalletBalance", "WalletHas", "WalletList", "WalletSign", "WalletSignMessage",
    # Mempool
    "MpoolBatchPush", "MpoolBatchPushUntrusted", "MpoolGetNonce", "MpoolPending",
    "MpoolPush", "MpoolPushMessage", "MpoolPushUntrusted", "MpoolSelect",
    # Search & Indexing
    "ChainGetEvents", "GetActorEventsRaw", "StateSearchMsg", "StateWaitMsg",
    # Node Operations
    "MinerCreateBlock", "MinerGetBaseInfo", "SyncSubmitBlock"
}

PRIMITIVE_MAPPING = {
    "integer": "int",
    "string": "string",
    "boolean": "bool",
    "object": "interface{}",
    "array": "[]interface{}", # default, can be refined
}

def get_go_type(schema):
    if "$ref" in schema:
        ref_name = schema["$ref"].split("/")[-1]
        if ref_name in TYPE_MAPPING:
            return TYPE_MAPPING[ref_name]
        return "interface{}"

    if "anyOf" in schema:
        for sub in schema["anyOf"]:
            if "type" in sub and sub["type"] == "null":
                continue
            return get_go_type(sub)
        return "interface{}"
    
    if "type" in schema:
        t = schema["type"]
        if isinstance(t, list):
            # If type is a list (e.g. ["string", "null"]), pick the first non-null type
            valid_types = [x for x in t if x != "null"]
            if len(valid_types) > 0:
                t = valid_types[0]
            else:
                return "interface{}"

        if t == "array":
            items = schema.get("items", {})
            elem_type = get_go_type(items)
            return "[]" + elem_type
        if t in PRIMITIVE_MAPPING:
            if t == "integer" and schema.get("format") == "int64":
                return "int64"
            return PRIMITIVE_MAPPING[t]
    
    return "interface{}"

def generate_api_struct(json_path, output_path):
    with open(json_path, "r") as f:
        data = json.load(f)
    
    methods = data.get("methods", [])
    
    lines = []
    lines.append("// Code generated by generate_go_struct.py; DO NOT EDIT.")
    lines.append("package resources")
    lines.append("")
    lines.append("import (")
    lines.append('\t"context"')
    lines.append("")
    lines.append('\t"github.com/filecoin-project/go-address"')
    lines.append('\t"github.com/filecoin-project/lotus/chain/types"')
    lines.append('\t"github.com/ipfs/go-cid"')
    lines.append(")")
    lines.append("")
    lines.append("type CommonAPI struct {")
    
    for method in methods:
        name = method["name"]
        if not name.startswith("Filecoin."):
            continue
        
        field_name = name.replace("Filecoin.", "")
        if field_name in EXCLUDED_METHODS:
            continue
        
        # Build params
        params = method.get("params", [])
        param_strs = ["context.Context"]
        for p in params:
            # name = p["name"] # Not used in signature, only type
            schema = p.get("schema", {})
            go_type = get_go_type(schema)
            param_strs.append(go_type)
        
        # Build result
        result = method.get("result", {})
        result_schema = result.get("schema", {})
        if not result_schema:
             # void? assume error only if no result? 
             # OpenRPC usually specifies result. If missing, maybe it's just error?
             # But the requirement says (<ResultType>, error).
             # If no result, maybe empty struct or just error?
             # Let's assume interface{} if missing, or maybe no return value?
             # Actually JSON-RPC always returns something or null.
             ret_type = "interface{}"
        else:
             ret_type = get_go_type(result_schema)
        
        params_sig = ", ".join(param_strs)
        
        # Field: MethodName func(ctx, params...) (Result, error)
        line = f"\t{field_name} func({params_sig}) ({ret_type}, error)"
        lines.append(line)
        
    lines.append("}")
    
    with open(output_path, "w") as f:
        f.write("\n".join(lines))

if __name__ == "__main__":
    generate_api_struct("common-node-api.json", "gen_api.go")
