name: filecoin
x-templates:
  filecoin_service: &filecoin_service
    env_file: .env
    volumes:
      - ./data/lotus0:${LOTUS_0_DATA_DIR}
      - ./data/forest0:${FOREST_0_DATA_DIR}
      - ./data/lotus1:${LOTUS_1_DATA_DIR}
      - ./shared/configs:${SHARED_CONFIGS}
  needs_drand0_started: &needs_drand0_started
    depends_on:
      drand0:
        condition: service_started

services:
  drand0:
    <<: [*filecoin_service]
    container_name: drand0
    image: drand
    entrypoint: ./start-drand0.sh
    networks:
      antithesis-net:
        ipv4_address: ${DRAND0_IP}
    healthcheck:
      test: drand util ping http://10.20.20.21:8080
      interval: 5s
      timeout: 2s
      retries: 10

  drand1:
    <<: [*filecoin_service, *needs_drand0_started]
    container_name: drand1
    image: drand
    entrypoint: ./start-drand1.sh
    networks:
      antithesis-net:
        ipv4_address: ${DRAND1_IP}
    healthcheck:
      test: drand util ping http://10.20.20.22:8080
      interval: 5s
      timeout: 2s
      retries: 10

  drand2:
    <<: [*filecoin_service, *needs_drand0_started]
    container_name: drand2
    image: drand
    entrypoint: ./start-drand2.sh
    networks:
      antithesis-net:
        ipv4_address: ${DRAND2_IP}
    healthcheck:
      test: drand util ping http://10.20.20.23:8080
      interval: 5s
      timeout: 2s
      retries: 10

networks:
  antithesis-net:
    ipam:
      config:
        - subnet: 10.20.20.0/24