name: Build & Push Workload

on: [workflow_dispatch]

jobs:
  antithesis:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Antithesis Google Artifact Registry
      uses: docker/login-action@v3
      with:
        registry: us-central1-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.ANTITHESIS_GAR_KEY }}

    - name: Extract metadata (tags) for Docker workload
      id: meta-workload
      uses: docker/metadata-action@v5
      with:
        images: us-central1-docker.pkg.dev/molten-verve-216720/filecoin-repository/workload
        tags: |
          type=sha
          latest
    - name: Build and push workload
      uses: docker/build-push-action@v5
      with:
        context: ./workload
        file: ./workload/Dockerfile
        push: true
        tags: ${{ steps.meta-workload.outputs.tags }}
        labels: ${{ steps.meta-workload.outputs.labels }}
